// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC_autoDB.Data;

namespace WebMVC_autoDB.Migrations
{
    [DbContext(typeof(WebMVC_autoDBContext))]
    [Migration("20210522065720_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMVC_autoDB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MyCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MyCategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ciekawe filmy po wojnie",
                            Name = "Wojenny"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tej ale miecz świetlny",
                            Name = "Scince fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rozgrzana rura",
                            Name = "Przygodowy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Misja ślimak",
                            Name = "Romantyczny"
                        });
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Film");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Duration = 120,
                            Title = "O jeden warkocz za dużo"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Duration = 130,
                            Title = "Big Papa"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Duration = 180,
                            Title = "Emeritos Banditos"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Duration = 140,
                            Title = "Musze bo sie udusze"
                        });
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Category", b =>
                {
                    b.HasOne("WebMVC_autoDB.Models.Category", "MyCategory")
                        .WithMany()
                        .HasForeignKey("MyCategoryId");

                    b.Navigation("MyCategory");
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Film", b =>
                {
                    b.HasOne("WebMVC_autoDB.Models.Category", "MyCategory")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyCategory");
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
